config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-kc/keycloak:
      branch: 22.0.3-staging
      repo: https://github.com/eosc-kc/keycloak
    github.com/keycloak/keycloak-documentation:
      branch: main
      repo: https://github.com/keycloak/keycloak-documentation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-cyan-eel.sh
        container: qc.acc_ugly-violet-eleuth
  QC.Doc:
    repos:
      github.com/keycloak/keycloak-documentation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-bronze-wallaby.sh
        container: qc.doc_ready-teal-lionfish
      github.com/keycloak/keycloak-documentation git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cerise-markhor.sh
        container: qc.doc_goopy-amber-spaniel
      github.com/keycloak/keycloak-documentation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-corn-gharial.sh
        container: qc.doc_tasty-buff-koala
  QC.Lic:
    repos:
      github.com/eosc-kc/keycloak licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-viridian-eagle.sh
        container: qc.lic_stuffy-sangria-monster
  QC.Sty:
    repos:
      github.com/eosc-kc/keycloak checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-beige-barnacle.sh
        container: qc.sty_homely-azure-frog
      github.com/eosc-kc/keycloak hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-champagne-fish.sh
        container: qc.sty_slimy-flax-sparrow
      github.com/eosc-kc/keycloak jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-jade-akbash.sh
        container: qc.sty_cranky-pink-crocodile
  QC.Ver:
    repos:
      github.com/eosc-kc/keycloak get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-charcoal-clam.sh
        container: qc.ver_snippy-thistle-eleuth
timeout: 5400
