config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-kc/keycloak:
      branch: 22.0.3-staging
      repo: https://github.com/eosc-kc/keycloak
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-pear-insect.sh
        container: qc.acc_baggy-cornflower-armadillo
  QC.Doc:
    repos:
      github.com/eosc-kc/keycloak find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-goldenrod-sponge.sh
        container: qc.doc_snippy-sepia-maltese
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-champagne-quoll.sh
        container: qc.doc_skimpy-sepia-opossum
      github.com/eosc-kc/keycloak markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cinnabar-zebra.sh
        container: qc.doc_breezy-black-greyhound
  QC.Lic:
    repos:
      github.com/eosc-kc/keycloak licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-malachite-avocet.sh
        container: qc.lic_tasty-scarlet-audemer
  QC.Met:
    repos:
      github.com/eosc-kc/keycloak validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-fuchsia-hyrax.sh
        container: qc.met_squirrely-pumpkin-sparrow
  QC.Sty:
    repos:
      github.com/eosc-kc/keycloak checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.ready-tomato-flounder.sh
        container: qc.sty_bumpy-aquamarine-blue
      github.com/eosc-kc/keycloak hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-aqua-wrasse.sh
        container: qc.sty_lousy-cornflower-corgi
      github.com/eosc-kc/keycloak jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-gold-whale.sh
        container: qc.sty_craggy-xanthic-cow
  QC.Ver:
    repos:
      github.com/eosc-kc/keycloak get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-taupe-dachsbracke.sh
        container: qc.ver_flimsy-aquamarine-hyena
timeout: 5400
