config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-kc/keycloak:
      branch: 22.0.3-staging
      repo: https://github.com/eosc-kc/keycloak
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-corn-earwig.sh
        container: qc.acc_paltry-cornflower-balinese
  QC.Doc:
    repos:
      github.com/eosc-kc/keycloak find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-rose-tuatara.sh
        container: qc.doc_flaky-cerise-chihuahua
      github.com/eosc-kc/keycloak git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-russet-hare.sh
        container: qc.doc_freaky-green-gecko
      github.com/eosc-kc/keycloak markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-red-duck.sh
        container: qc.doc_boozy-brass-bracke
  QC.Lic:
    repos:
      github.com/eosc-kc/keycloak licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-teal-saola.sh
        container: qc.lic_homely-azure-bulldog
  QC.Met:
    repos:
      github.com/eosc-kc/keycloak validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-mauve-kangaroo.sh
        container: qc.met_slimy-ecru-wallaby
  QC.Sty:
    repos:
      github.com/eosc-kc/keycloak checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-saffron-husky.sh
        container: qc.sty_surly-orchid-axolotl
      github.com/eosc-kc/keycloak hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-chartreuse-reindeer.sh
        container: qc.sty_thirsty-green-frog
      github.com/eosc-kc/keycloak jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-turquoise-jackal.sh
        container: qc.sty_foggy-periwinkle-frigatebird
  QC.Ver:
    repos:
      github.com/eosc-kc/keycloak get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-green-wolf.sh
        container: qc.ver_wimpy-scarlet-hyrax
timeout: 5400
